### ISSUE TITLE
Isolated Engine?

### ISSUE THREAD

**Issue by winston** [choonkeat/active_waiter#11]
The requirement for the parent app to prefix links in the layout (if configured to be used by the engine) with `main_app.` is probably an effect of this being an `isolated_engine`.

http://edgeapi.rubyonrails.org/classes/Rails/Engine.html

Do we want to make this a non-isolated engine instead?

**Comment by choonkeat** [comment]
> Do we want to make this a non-isolated engine instead?

What are the new caveats?

**Comment by winston** [comment]
> What are the new caveats?

Possible (controller) name conflicts, routes clashes.

**Comment by winston** [comment]
Looked into this.. and the implementation is actually not as nice.

If we remove `isolate_engine`, then this would also have to go from the main app:

``` diff
-     mount ActiveWaiter::Engine => "/active_waiter(/:id)"
```

This is because it is no longer is a `mountable` engine, but a `full` engine.

This describes it pretty well:

> In a full engine, the parent application inherits all of the routes defined in the engine, so it is not necessary to define anything in parent/config/routes.rb. Simply specifying the Engine in the gem file of the parent application is enough for it to have access to all of the engines models, controllers, routes, etc. For a mountable engine, its namespace is isolated by default
> Source: https://www.bignerdranch.com/blog/intro-to-rails-engines/

As such, I would prefer to continue using it as a `mountable` engine.

The documentation for `engines` in Rails does talk about the use of `main_app`, so I am probably not so worried about it any more.

Closing this. Ok?

**Comment by choonkeat** [comment]
:+1:
